name: 'Version Bump'
description: 'Automatically bump version based on conventional commits'
inputs:
  bump_type:
    description: 'Type of version bump (auto, patch, minor, major)'
    required: false
    default: 'auto'
  skip_release:
    description: 'Skip release creation if true'
    required: false
    default: 'false'
  dry_run:
    description: 'Run in dry-run mode without making changes'
    required: false
    default: 'false'
outputs:
  new_version:
    description: 'The new version that was created'
    value: ${{ steps.version.outputs.new_version }}
  bump_type:
    description: 'The type of bump that was performed'
    value: ${{ steps.version.outputs.bump_type }}
  last_version:
    description: 'The previous version'
    value: ${{ steps.version.outputs.last_version }}
  skip_release:
    description: 'Whether release was skipped'
    value: ${{ steps.version.outputs.skip_release }}
  changelog:
    description: 'Generated changelog content'
    value: ${{ steps.changelog.outputs.changelog }}
runs:
  using: 'composite'
  steps:
    - name: Determine version bump
      id: version
      shell: bash
      run: |
        set -e

        # Get last tag
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        LAST_VERSION=${LAST_TAG#v}

        # Parse version
        IFS='.' read -ra VERSION_PARTS <<< "$LAST_VERSION"
        MAJOR=${VERSION_PARTS[0]}
        MINOR=${VERSION_PARTS[1]}
        PATCH=${VERSION_PARTS[2]}

        BUMP_TYPE="${{ inputs.bump_type }}"

        if [ "$BUMP_TYPE" = "auto" ]; then
          # Get commits since last tag
          COMMITS_SINCE_TAG=$(git rev-list $LAST_TAG..HEAD --count 2>/dev/null || echo "1")

          if [ "$COMMITS_SINCE_TAG" -eq 0 ]; then
            echo "No new commits since last tag. Skipping version bump."
            echo "skip_release=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Determine bump type based on conventional commits
          BUMP_TYPE="patch"  # default

          # Check for major changes (breaking changes)
          if git log $LAST_TAG..HEAD --oneline | grep -q "BREAKING CHANGE\|feat!:\|fix!:\|refactor!:"; then
            BUMP_TYPE="major"
          # Check for minor changes (new features)
          elif git log $LAST_TAG..HEAD --oneline | grep -q "^feat:"; then
            BUMP_TYPE="minor"
          # Check for patch changes (fixes)
          elif git log $LAST_TAG..HEAD --oneline | grep -q "^fix:\|^perf:"; then
            BUMP_TYPE="patch"
          fi
        fi

        # Calculate new version
        case $BUMP_TYPE in
          major)
            NEW_MAJOR=$((MAJOR + 1))
            NEW_VERSION="$NEW_MAJOR.0.0"
            ;;
          minor)
            NEW_MINOR=$((MINOR + 1))
            NEW_VERSION="$MAJOR.$NEW_MINOR.0"
            ;;
          patch)
            NEW_PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
            ;;
          *)
            echo "Invalid bump type: $BUMP_TYPE"
            exit 1
            ;;
        esac

        echo "Last version: $LAST_VERSION"
        echo "New version: $NEW_VERSION"
        echo "Bump type: $BUMP_TYPE"
        echo "Skip release: ${{ inputs.skip_release }}"

        echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "bump_type=$BUMP_TYPE" >> $GITHUB_OUTPUT
        echo "last_version=$LAST_VERSION" >> $GITHUB_OUTPUT
        echo "skip_release=${{ inputs.skip_release }}" >> $GITHUB_OUTPUT

    - name: Update composer.json
      if: steps.version.outputs.skip_release == 'false' && inputs.dry_run == 'false'
      shell: bash
      run: |
        NEW_VERSION="${{ steps.version.outputs.new_version }}"
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/" composer.json
        echo "Updated composer.json to version $NEW_VERSION"

    - name: Generate changelog
      id: changelog
      shell: bash
      run: |
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "HEAD~1")
        BUMP_TYPE="${{ steps.version.outputs.bump_type }}"
        NEW_VERSION="${{ steps.version.outputs.new_version }}"

        # Generate changelog from commits
        if [ "$LAST_TAG" = "HEAD~1" ]; then
          # First release
          COMMITS=$(git log --oneline --pretty=format:"%s" | head -10)
        else
          COMMITS=$(git log --oneline --pretty=format:"%s" $LAST_TAG..HEAD)
        fi

        # Create changelog content
        CHANGELOG="## What's Changed\\n\\n"
        CHANGELOG+="### ${{ steps.version.outputs.bump_type == 'major' && 'Breaking Changes' || steps.version.outputs.bump_type == 'minor' && 'New Features' || 'Bug Fixes' }}\\n"
        CHANGELOG+="- ${{ steps.version.outputs.bump_type }} version bump to ${{ steps.version.outputs.new_version }}\\n\\n"

        if [ -n "$COMMITS" ]; then
          CHANGELOG+="### Commits\\n"
          while IFS= read -r commit; do
            CHANGELOG+="- $commit\\n"
          done <<< "$COMMITS"
          CHANGELOG+="\\n"
        fi

        CHANGELOG+="---\\n"
        CHANGELOG+="**Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ steps.version.outputs.last_version }}...v${{ steps.version.outputs.new_version }}"

        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo -e "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Update CHANGELOG.md
      if: steps.version.outputs.skip_release == 'false' && inputs.dry_run == 'false'
      shell: bash
      run: |
        DATE=$(date +%Y-%m-%d)
        NEW_VERSION="${{ steps.version.outputs.new_version }}"
        BUMP_TYPE="${{ steps.version.outputs.bump_type }}"

        SECTION_NAME=$([ "$BUMP_TYPE" = "major" ] && echo "Changed" || [ "$BUMP_TYPE" = "minor" ] && echo "Added" || echo "Fixed")

        # Insert new entry at the top (after title)
        sed -i "4a ## [$NEW_VERSION] - $DATE\\n\\n### $SECTION_NAME\\n- $BUMP_TYPE version bump\\n" CHANGELOG.md
        echo "Updated CHANGELOG.md with version $NEW_VERSION"

    - name: Dry run summary
      if: inputs.dry_run == 'true'
      shell: bash
      run: |
        echo "🔍 Dry run mode - no files were modified"
        echo "📦 Would bump version: ${{ steps.version.outputs.last_version }} → ${{ steps.version.outputs.new_version }}"
        echo "🎯 Bump type: ${{ steps.version.outputs.bump_type }}"
        echo "📝 Generated changelog:"
        echo "${{ steps.changelog.outputs.changelog }}"
